version: '3.7'
services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    restart: always

  iotdb:
    image: apache/iotdb:1.3.0-standalone
    ports:
      - "6667:6667"
      - "18080:18080"
    volumes:
      - iotdb-data:/iotdb/data
      - iotdb-logs:/iotdb/logs
    restart: always

volumes:
  node-red-data:
  iotdb-data:
  iotdb-logs: